version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: tournament_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/tournament_db.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    depends_on:
      - postgres
    ports:
<<<<<<< Updated upstream
      - "8081:8081"
=======
      - "8081:8080"
>>>>>>> Stashed changes
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 3600000
